### ISSUE TITLE
ToonUnlit.shadergraph asset fails to import

### ISSUE THREAD

**Issue by MvnTruong** [lchaumartin/URPToonShading#1]
I tried opening up the project, but the shadergraph file fails to import. The error says:

`Asset import failed, "Assets/ToonUnlit.shadergraph" > ArgumentException: JSON parse error: The document root must not follow by other values.`

I'm using Unity 2020.1.5f1

Edit: Yes, the project is URP

**Comment by Wally869** [comment]
Same issue on 2019.4.11f1 when importing the shader in a new project, with URP 7.3.1
In Unity 2020.2.6f1 I get missing errors from ShaderGraph.serialization for URP 10.3.1

I checked the whole shadergraph, all nodes are valid JSON so this seems to be an problem of compatibility between URP versions? 

@lchaumartin Can you please tell us which version of Unity and URP you are using? Thanks a lot. 
Also, it might be a good idea to add a package release to this repo for easier use?

**Comment by Wally869** [comment]
Managed to import in 2020.2.6f1, I think the problem was due to my import settings? (asset serialization mode was set to binary)
Feature works as expected, thanks for sharing your work!

**Comment by lchaumartin** [comment]
I made the shadergraph using unity 2019.4 and URP 7.5.2, but updated it using Unity 2020.3 and URP 10.4.0, which was probably a the source of the problem. 
I rolled back to the first commit and applied the few minor fixes using only URP 7.5.2 this time, so it should be fixed now. Sorry for this mistake.
